pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.0.100'
- script: |
    dotnet tool restore
    dotnet run --project tests/tests.fsproj
  displayName: 'SAFE Template tests'
