name: SAFE Template release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool restore
        run: dotnet tool restore

      - name: Package
        env:
          VERSION: ${{ github.ref_name }}
          RELEASE_NOTES_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES_BODY: ${{ github.event.release.body }}
        run: dotnet run --project Build.fsproj -- Package

      - name: Publish
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
